CREATE TABLE IF NOT EXISTS currency_pairs(
  id        BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  symbol    VARCHAR(6) NOT NULL UNIQUE
);

INSERT INTO currency_pairs (symbol)
VALUES  ('AUDCAD'),
        ('AUDCHF'),
        ('AUDJPY'),
        ('AUDNZD'),
        ('AUDUSD'),
        ('BGNRON'),
        ('CADCHF'),
        ('CADJPY'),
        ('CHFBGN'),
        ('CHFJPY'),
        ('CHFRON'),
        ('CHFTRY'),
        ('EURAUD'),
        ('EURCAD'),
        ('EURCHF'),
        ('EURCZK'),
        ('EURDKK'),
        ('EURGBP'),
        ('EURHKD'),
        ('EURHUF'),
        ('EURILS'),
        ('EURJPY'),
        ('EURMXN'),
        ('EURNOK'),
        ('EURNZD'),
        ('EURPLN'),
        ('EURRON'),
        ('EURRUB'),
        ('EURSEK'),
        ('EURSGD'),
        ('EURTRY'),
        ('EURUSD'),
        ('EURZAR'),
        ('GBPAUD'),
        ('GBPBGN'),
        ('GBPCAD'),
        ('GBPCHF'),
        ('GBPCZK'),
        ('GBPDKK'),
        ('GBPHKD'),
        ('GBPHUF'),
        ('GBPJPY'),
        ('GBPNOK'),
        ('GBPNZD'),
        ('GBPPLN'),
        ('GBPRON'),
        ('GBPSEK'),
        ('GBPSGD'),
        ('GBPTRY'),
        ('GBPUSD'),
        ('GBPZAR'),
        ('HKDJPY'),
        ('NZDCAD'),
        ('NZDCHF'),
        ('NZDJPY'),
        ('NZDUSD'),
        ('SGDHKD'),
        ('SGDJPY'),
        ('TRYBGN'),
        ('TRYJPY'),
        ('TRYRON'),
        ('USDBGN'),
        ('USDCAD'),
        ('USDCHF'),
        ('USDCZK'),
        ('USDDKK'),
        ('USDHKD'),
        ('USDHUF'),
        ('USDILS'),
        ('USDJPY'),
        ('USDMXN'),
        ('USDNOK'),
        ('USDPLN'),
        ('USDRON'),
        ('USDRUB'),
        ('USDSEK'),
        ('USDSGD'),
        ('USDTRY'),
        ('USDZAR');

CREATE TABLE IF NOT EXISTS price_action_types(
  id            BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
  price_action  VARCHAR(255)
);

INSERT INTO price_action_types(price_action)
VALUES  ('Engulfing Bar'),
        ('Doji'),
        ('Dragonfly Doji'),
        ('GraveStone Doji'),
        ('Morning star'),
        ('Evening star'),
        ('Hammer'),
        ('Shooting star'),
        ('Harami'),
        ('Spinning tops'),
        ('Tweezer Top'),
        ('Tweezer Bottom'),
        ('Three black crows'),
        ('Three inside up'),
        ('Three inside down'),
        ('Three white soldiers');

CREATE TABLE IF NOT EXISTS timeframe(
  id          BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
  timeframe   VARCHAR(3),
  description VARCHAR(255)
);

INSERT INTO timeframe(timeframe, description)
VALUES  ('M1','One minute'),
        ('M5','five minutes'),
        ('M15','fifteen minutes'),
        ('M30','Thirty minutes'),
        ('H1','One hour'),
        ('H4','Four hours'),
        ('D1','One day'),
        ('W1','One week'),
        ('MN','One Month');
